package com.sub.nit.getparameter;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/submitForm")
public class MyServlet5 extends HttpServlet {

    @Override
    protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // Set content type to HTML
        resp.setContentType("text/html;charset=UTF-8");
        
        // Get form data
        String name = req.getParameter("name1");
        String email = req.getParameter("email1");
        String paswd = req.getParameter("paswd1");
        String loc = req.getParameter("Loc1");

        // Print to console (for debugging)
        System.out.println("Name is: " + name);
        System.out.println("Email is: " + email);
        System.out.println("Password is: " + paswd);
        System.out.println("Location is: " + loc);
        System.out.println("Thank you..:");

        // Send animated success page
        PrintWriter out = resp.getWriter();
        out.println("<!DOCTYPE html>");
        out.println("<html lang='en'>");
        out.println("<head>");
        out.println("<meta charset='UTF-8'>");
        out.println("<title>Registration Success ✨</title>");
        out.println("<style>");
        out.println("/* Animated Stars Background */");
        out.println("body {");
        out.println("    margin: 0;");
        out.println("    padding: 0;");
        out.println("    height: 100vh;");
        out.println("    font-family: 'Arial', sans-serif;");
        out.println("    background: radial-gradient(ellipse at bottom, #1b2735 0%, #090a0f 100%);");
        out.println("    overflow: hidden;");
        out.println("    position: relative;");
        out.println("    display: flex;");
        out.println("    justify-content: center;");
        out.println("    align-items: center;");
        out.println("}");
        out.println("");
        out.println("/* Stars Container */");
        out.println(".stars {");
        out.println("    position: absolute;");
        out.println("    top: 0;");
        out.println("    left: 0;");
        out.println("    width: 100%;");
        out.println("    height: 100%;");
        out.println("    pointer-events: none;");
        out.println("}");
        out.println("");
        out.println(".star {");
        out.println("    position: absolute;");
        out.println("    background: white;");
        out.println("    border-radius: 50%;");
        out.println("    animation: twinkle 2s infinite ease-in-out;");
        out.println("}");
        out.println("");
        out.println(".star:nth-child(1) { width: 2px; height: 2px; top: 10%; left: 10%; animation-delay: 0s; }");
        out.println(".star:nth-child(2) { width: 3px; height: 3px; top: 20%; left: 20%; animation-delay: 0.2s; }");
        out.println(".star:nth-child(3) { width: 1px; height: 1px; top: 30%; left: 30%; animation-delay: 0.4s; }");
        out.println(".star:nth-child(4) { width: 2px; height: 2px; top: 40%; left: 40%; animation-delay: 0.6s; }");
        out.println(".star:nth-child(5) { width: 4px; height: 4px; top: 50%; left: 50%; animation-delay: 0.8s; }");
        out.println(".star:nth-child(6) { width: 1.5px; height: 1.5px; top: 60%; left: 60%; animation-delay: 1s; }");
        out.println(".star:nth-child(7) { width: 3px; height: 3px; top: 70%; left: 70%; animation-delay: 1.2s; }");
        out.println(".star:nth-child(8) { width: 2px; height: 2px; top: 80%; left: 80%; animation-delay: 1.4s; }");
        out.println(".star:nth-child(9) { width: 1px; height: 1px; top: 15%; left: 70%; animation-delay: 1.6s; }");
        out.println(".star:nth-child(10) { width: 2.5px; height: 2.5px; top: 25%; left: 85%; animation-delay: 1.8s; }");
        out.println("");
        out.println("/* Twinkling animation */");
        out.println("@keyframes twinkle {");
        out.println("    0%, 100% { opacity: 0.3; transform: scale(1); }");
        out.println("    50% { opacity: 1; transform: scale(1.2); }");
        out.println("}");
        out.println("");
        out.println("/* Success Card */");
        out.println(".success-card {");
        out.println("    background: rgba(255, 255, 255, 0.95);");
        out.println("    backdrop-filter: blur(15px);");
        out.println("    padding: 40px 30px;");
        out.println("    border-radius: 25px;");
        out.println("    box-shadow: 0 25px 50px rgba(0,0,0,0.4);");
        out.println("    text-align: center;");
        out.println("    max-width: 450px;");
        out.println("    width: 90%;");
        out.println("    animation: cardSlideIn 1.2s cubic-bezier(0.25, 0.46, 0.45, 0.94);");
        out.println("    position: relative;");
        out.println("    z-index: 10;");
        out.println("}");
        out.println("");
        out.println("@keyframes cardSlideIn {");
        out.println("    0% { opacity: 0; transform: translateY(60px) scale(0.8); }");
        out.println("    100% { opacity: 1; transform: translateY(0) scale(1); }");
        out.println("}");
        out.println("");
        out.println(".success-icon {");
        out.println("    font-size: 80px;");
        out.println("    margin-bottom: 20px;");
        out.println("    animation: bounce 2s infinite;");
        out.println("}");
        out.println("");
        out.println("@keyframes bounce {");
        out.println("    0%, 20%, 50%, 80%, 100% { transform: translateY(0); }");
        out.println("    40% { transform: translateY(-15px); }");
        out.println("    60% { transform: translateY(-8px); }");
        out.println("}");
        out.println("");
        out.println("h1 {");
        out.println("    color: #1a237e;");
        out.println("    margin: 0 0 20px 0;");
        out.println("    font-size: 32px;");
        out.println("    animation: glow 2s ease-in-out infinite alternate;");
        out.println("}");
        out.println("");
        out.println("@keyframes glow {");
        out.println("    from { text-shadow: 0 0 15px rgba(26, 35, 126, 0.6); }");
        out.println("    to { text-shadow: 0 0 25px rgba(26, 35, 126, 0.9), 0 0 35px rgba(26, 35, 126, 0.5); }");
        out.println("}");
        out.println("");
        out.println(".user-name {");
        out.println("    color: #3f51b5;");
        out.println("    font-size: 28px;");
        out.println("    font-weight: bold;");
        out.println("    margin: 15px 0;");
        out.println("    animation: namePulse 1.5s ease-in-out infinite;");
        out.println("}");
        out.println("");
        out.println("@keyframes namePulse {");
        out.println("    0%, 100% { transform: scale(1); }");
        out.println("    50% { transform: scale(1.05); }");
        out.println("}");
        out.println("");
        out.println(".details {");
        out.println("    background: rgba(255, 255, 255, 0.7);");
        out.println("    padding: 20px;");
        out.println("    border-radius: 15px;");
        out.println("    margin: 25px 0;");
        out.println("    text-align: left;");
        out.println("}");
        out.println("");
        out.println(".detail-item {");
        out.println("    margin: 12px 0;");
        out.println("    padding: 8px 0;");
        out.println("    border-left: 4px solid #3f51b5;");
        out.println("    padding-left: 15px;");
        out.println("    animation: slideInLeft 0.8s ease forwards;");
        out.println("}");
        out.println("");
        out.println(".detail-item:nth-child(1) { animation-delay: 0.2s; }");
        out.println(".detail-item:nth-child(2) { animation-delay: 0.4s; }");
        out.println(".detail-item:nth-child(3) { animation-delay: 0.6s; }");
        out.println("");
        out.println("@keyframes slideInLeft {");
        out.println("    from { opacity: 0; transform: translateX(-30px); }");
        out.println("    to { opacity: 1; transform: translateX(0); }");
        out.println("}");
        out.println("");
        out.println(".home-btn {");
        out.println("    background: linear-gradient(45deg, #1a237e, #3f51b5);");
        out.println("    color: white;");
        out.println("    border: none;");
        out.println("    padding: 15px 30px;");
        out.println("    border-radius: 50px;");
        out.println("    font-size: 18px;");
        out.println("    font-weight: 600;");
        out.println("    cursor: pointer;");
        out.println("    margin-top: 25px;");
        out.println("    transition: all 0.4s ease;");
        out.println("    box-shadow: 0 10px 25px rgba(26, 35, 126, 0.4);");
        out.println("}");
        out.println("");
        out.println(".home-btn:hover {");
        out.println("    transform: translateY(-5px) scale(1.05);");
        out.println("    box-shadow: 0 20px 40px rgba(26, 35, 126, 0.6);");
        out.println("}");
        out.println("");
        out.println("@media (max-width: 480px) {");
        out.println("    .success-card { padding: 30px 20px; }");
        out.println("    h1 { font-size: 26px; }");
        out.println("    .user-name { font-size: 24px; }");
        out.println("}");
        out.println("</style>");
        out.println("</head>");
        out.println("<body>");
        out.println("    <!-- Animated Stars -->");
        out.println("    <div class='stars'>");
        for(int i = 1; i <= 10; i++) {
            out.println("        <div class='star'></div>");
        }
        out.println("    </div>");
        out.println("");
        out.println("    <div class='success-card'>");
        out.println("        <div class='success-icon'>✨</div>");
        out.println("        <h1>Registration Successful!</h1>");
        out.println("        <div class='user-name'>" + name + "</div>");
        out.println("        <div class='details'>");
        out.println("            <div class='detail-item'><strong>📧 Email:</strong> " + email + "</div>");
        out.println("            <div class='detail-item'><strong>📍 Location:</strong> " + loc + "</div>");
        out.println("            <div class='detail-item'><strong>✅ Account Created</strong></div>");
        out.println("        </div>");
        out.println("        <button class='home-btn' onclick='history.back()'>← Back to Form</button>");
        out.println("    </div>");
        out.println("</body>");
        out.println("</html>");
    }
} 
